<?php

define("WPCLOAKER_CLOAK", 0);
define("WPCLOAKER_REDIRECT", 1);
define("WPCLOAKER_NONE", 2);
define("WPCLOAKER_FRAME", 3);

define("WPCLOAKER_IP", 0);
define("WPCLOAKER_UA", 1);
define("WPCLOAKER_IP_UA", 2);
define("WPCLOAKER_REFERRER", 3);
define("WPCLOAKER_LANG", 4);
define("WPCLOAKER_GEOIP_COUNTRY", 5);
define("WPCLOAKER_IP_UA_REFERRER", 6);
define("WPCLOAKER_ALWAYS_CLOAK", 7);
define("WPCLOAKER_IP_GEOIP", 8);

define("WPCLOAKER_VERSION", '1.99-20150624-1');

?>